spring:
  datasource:
    url: jdbc:postgresql://dpg-cj0icbs07spl5opga080-a.oregon-postgres.render.com:5432/po_jdaz
    driver-class-name: org.postgresql.Driver
    username: po_jdaz_user
    password: dpg-cj0icbs07spl5opga080-a.oregon-postgres.render.com

#      url: jdbc:postgresql://localhost:5432/popdb
#  postgres://po_jdaz_user:fs5d1kGK5G3F0J0fVuVGhAMZiIg7MikV@dpg-cj0icbs07spl5opga080-a.oregon-postgres.render.com/po_jdaz
#      driver-class-name: org.postgresql.Driver
#      username: postgres
#      password: 123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
