spring:
  datasource:
    url: jdbc:postgresql://dpg-cj1566c07spjv9qahrrg-a.oregon-postgres.render.com:5432/po_7ffo
    driver-class-name: org.postgresql.Driver
    username: po_7ffo_user
    password: zNr2PmQki1ABt3hGtWvPy9dq5i3k4bvU


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
